language: swift

stages:
  - name: CocoapodsLint
    if: NOT branch =~ ^\d+\.\d+\.\d+$
  - name: CarthageBuild
    if: type != push OR branch =~ /^\d+\.\d+\.\d+$/
  - name: Test
    if: type != push OR branch =~ /^\d+\.\d+\.\d+$/
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:

    - &pod
      stage: CocoapodsLint
      install: gem install cocoapods -v '~> 1.8.1'
      script: pod lib lint --allow-warnings --fail-fast
      osx_image: xcode10.3
    - <<: *pod
      osx_image: xcode11

    - &carthage
      stage: CarthageBuild
      script: carthage build --no-skip-current
      osx_image: xcode10.3
      name: Xcode 10.3
    - <<: *carthage
      osx_image: xcode11
      name: Xcode 11

    - &test
      stage: Test
      name: iOS 12.2 / Xcode 10.3
      xcode_workspace: Example/TaggerKit.xcworkspace
      xcode_scheme: TaggerKit-Example
      osx_image: xcode10.3
      xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone SE
    - <<: *test
      name: iOS 13.0 / Xcode 11
      osx_image: xcode11
      xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone Xs

    - name: '`pod trunk push`'
      stage: Deploy
      install: gem install cocoapods -v '~> 1.8.1'
      before_script: |
        mv .github/TaggerKit.podspec .
        sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" TaggerKit.podspec
      script: |
        set -exo pipefail
        pod trunk push --verbose --allow-warnings | tee pod.log | ruby -e 'ARGF.each{ print "." }'
      after_failure: cat pod.log | grep error
