osx_image: xcode11
language: swift
xcode_workspace: Example/TaggerKit.xcworkspace
xcode_scheme: TaggerKit-Example
xcode_destination: platform=iOS Simulator,OS=13,name=iPhone X

before_script: set -o pipefail && xcodebuild clean
after_success: pod lib lint