osx_image: xcode11
language: swift
xcode_workspace: Example/TaggerKit.xcworkspace
xcode_scheme: TaggerKit
xcode_destination: platform=iOS Simulator,OS=13,name=iPhone X

jobs:
  include:
    - stage: clean
      script: set -o pipefail && xcodebuild clean
    - stage: test&build
      script: set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TaggerKit.xcworkspace -scheme TaggerKit-Example ONLY_ACTIVE_ARCH=NO | xcpretty
    - stage: podLint
      script: pod lib lint