osx_image: xcode11
language: swift
xcode_workspace: Example/TaggerKit.xcworkspace
xcode_scheme: TaggerKit
xcode_destination: platform=iOS Simulator,OS=13,name=iPhone X

branches:
  only:
    - develop
    - master

jobs:
  include:
    - stage: clean
      before_script: set -o pipefail && xcodebuild clean
    - stage: podLint
      after_success: pod lib lint