osx_image: xcode11
language: swift
xcode_project: Example/TaggerKit.xcodeproj 
xcode_scheme: TaggerKit
xcode_destination: platform=iOS Simulator,OS=13,name=iPhone X

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TaggerKit.xcworkspace -scheme TaggerKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
